- name: Configure CentOS VMs
  hosts: all
  become: true
  tasks:
    - name: Update /etc/hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item].ansible_host }} {{ item }}"
      loop: "{{ groups['centos'] }}"

    - name: Update cat /etc/resolv.conf 
    file
      lineinfile:
        path: /etc/resolv.conf
        line: "{{ item }}"
        src: resolv.conf.j2
        dest: /etc/resolv.conf
        backup: yes
      with_items:
        - "nameserver 8.8.8.8"
        - "nameserver 8.8.4.4"

    - name: Update /etc/chrony.conf file
      copy:
        content: |
          server time1.google.com iburst
          server time2.google.com iburst
        dest: /etc/chrony.conf
